services:
  cache:
    container_name: cache
    image: docker.io/redis:8.0-M03-alpine
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
      - ${CERT_PATH}:/certs/redis.crt
      - ${CERT_KEY_PATH}:/certs/redis.key
      - ${CA_CERT_PATH}:/certs/ca.crt
    command: 'redis-server /usr/local/etc/redis/redis.conf'

  web:
    container_name: web
    build: .
    restart: always
    env_file: .env
    environment:
      - TZ=America/Lima

  proxy:
    container_name: proxy
    image: docker.io/nginx:alpine-slim
    restart: always
    env_file: .env
    environment:
      - TZ=America/Lima
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${CERT_PATH}:/etc/nginx/certs/cert.pem
      - ${CERT_KEY_PATH}:/etc/nginx/certs/key.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
