services:
  com:
    container_name: com.loadept
    build: .
    env_file: .env
    environment:
      - TZ=America/Lima
      - PORT=${PORT}

  proxy:
    container_name: proxy.loadept
    image: nginx:alpine-slim
    env_file: .env
    environment:
      - TZ=America/Lima
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${CERT_PATH}:/etc/nginx/certs/cert.pem
      - ${CERT_KEY_PATH}:/etc/nginx/certs/key.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - com
