services:
  cache:
    container_name: cache
    image: redis:8.0-M03-alpine

  web:
    container_name: web
    build: .
    env_file: .env
    environment:
      - TZ=America/Lima

      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - REDIS_ADDR=cache
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - GITHUB_API=${GITHUB_API}
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  proxy:
    container_name: proxy
    image: nginx:alpine-slim
    env_file: .env
    environment:
      - TZ=America/Lima
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${CERT_PATH}:/etc/nginx/certs/cert.pem
      - ${CERT_KEY_PATH}:/etc/nginx/certs/key.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
