name: Server tests

on:
  push:
    branches: [main]

jobs:
  Unit-Testing:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git log -1

      - name: Download go lang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      - run: go version

      - name: Start unit testing
        run: |
          testable_paths=$(go list ./... | grep -v "test/") 
          go test -v $testable_paths

  Integration-Testing:
    environment: testing

    runs-on: ubuntu-24.04
    needs:
      - Unit-Testing
    if: success()

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_USER: ""
      REDIS_PASSWORD: ""
      REDIS_TLS_INSECURE: "true"
      GITHUB_API: "${{ secrets.GB_API }}"
      GITHUB_TOKEN: "${{ secrets.GB_TOKEN }}"
  
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git log -1

      - name: Download go lang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      - run: go version

      - name: Start integration testing
        run: |
          go test -v ./test/...
